### ISSUE TITLE
Question: Howto change format of file size and timestamp output by ls -l?

### ISSUE THREAD

**Issue by boskamp** [dropbox/dbxcli#110]
Is it possible to customize the format of file size and timestamp output by ls -l? I would like to display file size in bytes, and timestamps in some canonical format like ISO8601.

My use case is that I have a local -presumably outdated- revision of my Dropbox tree. I can inspect the files and folder of that local revision using Linux ls -lR, of course. What I would like to have is the exact same information for my remote Dropbox tree, so I can canonicalize and diff local vs. remote using a script I will write for that purpose.

dbxcli ls -lR provides close to what I need, just the timestamps and file sizes from both tools are not really comparable.

**Comment by mpr90** [comment]
Looks like a code change would be required to match the "ls -l" timestamp behaviour. Currently time is "humanized" by the code. Suggest maybe only doing this when a new "-h" option is given and otherwise following ls behaviour as suggested [here](https://stackoverflow.com/questions/36440416/formatting-date-time-in-the-same-way-as-ls-l-command).

**Comment by boskamp** [comment]
Thanks, I was able to implement the behavior I need by patching cmd/ls.go. 

The changes needed, as far as I remember, were one additional import "time" and a change to func printFileMetadata(w io.Writer, e *files.FileMetadata, longFormat bool), replacing
````
humanize.Time(e.ServerModified)
````
with
````
e.ServerModified.UTC().Format(time.RFC3339)
````
