### ISSUE TITLE
Invalid client_id when trying to get authorization code

### ISSUE THREAD

**Issue by mndrix** [dropbox/dbxcli#79]
I've installed dbxcli via "go get" since binaries are not available for OpenBSD.  When I copy and paste the OAuth URL I get this error:

```
Error (400)
It seems the app you were using submitted a bad request. If you would like to report this error to the app's developer, include the information below.


More details for developers
Invalid client_id: "mvhz183vwqibe7q".
```

Issue #62 resolved this problem by installing the latest binaries.  Since those aren't available for my platform, how should I proceed?  Thanks.

**Comment by diwakergupta** [comment]
@mndrix yes, 'go get' won't work because the credentials in the code base are "dummy". If you are really motivated, you can register your own apps (https://www.dropbox.com/developers/apps) and build using your own credentials. It'll be simpler though for me to just add OpenBSD to the list of generated binaries -- only caveat is that I have no way of testing them, so you'll be on your own there.

LMK if that works for you and I can generate a new release with OpenBSD binaries. Can you provide the exact OS/Arch combo you are using?

**Comment by mndrix** [comment]
That sounds good to me.

```
$ uname -srp
OpenBSD 6.1 amd64
```

**Comment by diwakergupta** [comment]
@mndrix try the binary from the latest releases page and LMK!

https://github.com/dropbox/dbxcli/releases/latest

**Comment by mndrix** [comment]
The OpenBSD binary release is working fine for me.  Thanks

**Comment by rustyx** [comment]
`dbxcli` should print a warning if started with dummy credentials, explaining the issue.

Not everyone reads installation instructions since `go install` is usually the way to install a Go tool.

And BTW, the instructions are incomplete as one also needs to add scopes (files.metadata.read, etc. are not enabled by default)
